/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Date;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Calendar;

/**
 *
 * @author anna_
 */
public class MainFrame extends javax.swing.JDialog {

    /**
     * Creates new form MainFrame
     */
    public MainFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        rebuildFacultyComboBoxes();
    }
    
    public void rebuildFacultyComboBoxes(){
        reserveFacultyComboBox.setModel(new javax.swing.DefaultComboBoxModel(Faculty.getFacultyList().toArray()));
        reserveDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getAllDates().toArray()));
        resStatusDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getAllDates().toArray()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        tabbedPanel = new javax.swing.JTabbedPane();
        addFacultyTab = new javax.swing.JPanel();
        addFacultyNameLabel = new javax.swing.JLabel();
        addFacultyNameField = new javax.swing.JTextField();
        addFacultyButton = new javax.swing.JButton();
        addFacultyResultLabel = new javax.swing.JLabel();
        reserveTab = new javax.swing.JPanel();
        reserveFacultyLabel = new javax.swing.JLabel();
        reserveFacultyComboBox = new javax.swing.JComboBox<>();
        reserveDateLabel = new javax.swing.JLabel();
        reserveDateComboBox = new javax.swing.JComboBox<>();
        reserveSeatsLabel = new javax.swing.JLabel();
        reserveSeatsField = new javax.swing.JTextField();
        reserveSubmitButton = new javax.swing.JButton();
        reserveResultLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        resStatusDateComboBox = new javax.swing.JComboBox<>();
        resStatusButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resStatusTextArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        waitListStatusButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        waitListStatusTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 0, 0));
        titleLabel.setText("Room Scheduler");

        addFacultyNameLabel.setText("Faculty Name:");

        addFacultyNameField.setColumns(20);

        addFacultyButton.setText("Submit");
        addFacultyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFacultyButtonActionPerformed(evt);
            }
        });

        addFacultyResultLabel.setText("       ");

        javax.swing.GroupLayout addFacultyTabLayout = new javax.swing.GroupLayout(addFacultyTab);
        addFacultyTab.setLayout(addFacultyTabLayout);
        addFacultyTabLayout.setHorizontalGroup(
            addFacultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFacultyTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addFacultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addFacultyTabLayout.createSequentialGroup()
                        .addComponent(addFacultyNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addFacultyNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addFacultyButton)
                    .addComponent(addFacultyResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(528, Short.MAX_VALUE))
        );
        addFacultyTabLayout.setVerticalGroup(
            addFacultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFacultyTabLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(addFacultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFacultyNameLabel)
                    .addComponent(addFacultyNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addFacultyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addFacultyResultLabel)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        tabbedPanel.addTab("Add Faculty", addFacultyTab);

        reserveFacultyLabel.setText("Faculty: ");

        reserveDateLabel.setText("Date: ");

        reserveSeatsLabel.setText("Seats: ");

        reserveSeatsField.setText("   ");

        reserveSubmitButton.setText("Submit");
        reserveSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveSubmitButtonActionPerformed(evt);
            }
        });

        reserveResultLabel.setText("      ");

        javax.swing.GroupLayout reserveTabLayout = new javax.swing.GroupLayout(reserveTab);
        reserveTab.setLayout(reserveTabLayout);
        reserveTabLayout.setHorizontalGroup(
            reserveTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reserveTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reserveTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reserveTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(reserveTabLayout.createSequentialGroup()
                            .addComponent(reserveFacultyLabel)
                            .addGap(30, 30, 30)
                            .addComponent(reserveFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(reserveTabLayout.createSequentialGroup()
                            .addComponent(reserveDateLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reserveDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(reserveTabLayout.createSequentialGroup()
                            .addComponent(reserveSeatsLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reserveSeatsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(reserveSubmitButton)
                    .addComponent(reserveResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(570, Short.MAX_VALUE))
        );
        reserveTabLayout.setVerticalGroup(
            reserveTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reserveTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reserveTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reserveFacultyLabel)
                    .addComponent(reserveFacultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(reserveTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reserveDateLabel)
                    .addComponent(reserveDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(reserveTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reserveSeatsLabel)
                    .addComponent(reserveSeatsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reserveSubmitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reserveResultLabel)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        tabbedPanel.addTab("Reserve", reserveTab);

        jLabel1.setText("Date:  ");

        resStatusButton.setText("Submit");
        resStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resStatusButtonActionPerformed(evt);
            }
        });

        resStatusTextArea.setColumns(20);
        resStatusTextArea.setRows(5);
        jScrollPane1.setViewportView(resStatusTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(33, 33, 33)
                                .addComponent(resStatusDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(resStatusButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(resStatusDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resStatusButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPanel.addTab("Reservation Status", jPanel1);

        waitListStatusButton.setText("Display");
        waitListStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waitListStatusButtonActionPerformed(evt);
            }
        });

        waitListStatusTextArea.setColumns(20);
        waitListStatusTextArea.setRows(5);
        jScrollPane2.setViewportView(waitListStatusTextArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(waitListStatusButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(waitListStatusButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPanel.addTab("Waitlist Status", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addGap(268, 268, 268))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabbedPanel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addFacultyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFacultyButtonActionPerformed
        // TODO add your handling code here:
        String name = addFacultyNameField.getText();
        Faculty.addFaculty(name);
        addFacultyResultLabel.setText(name+" has been added to the Faculty.");
        
        // rebuild the reservation faculty combo box.
        rebuildFacultyComboBoxes();
    }//GEN-LAST:event_addFacultyButtonActionPerformed

    private void resStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resStatusButtonActionPerformed
        // TODO add your handling code here:
        String sDate = String.valueOf(resStatusDateComboBox.getSelectedItem());
        Date date = Date.valueOf(sDate);
        
        ArrayList<ReservationEntry> reservations = ReservationQueries.getReservationsByDate(date);
        String output = "";
        
        for(ReservationEntry entry : reservations){
            output += entry.getName() + " reserves " + entry.getRoom() + "\n";
        }
        
        resStatusTextArea.setText(output);
    }//GEN-LAST:event_resStatusButtonActionPerformed

    private void waitListStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waitListStatusButtonActionPerformed
        // TODO add your handling code here:
        ArrayList<Date> dates = Dates.getAllDates();
        String output = "";
        
        for(Date date : dates){
            ArrayList<WaitListEntry> entries = WaitListQueries.getWaitListEntriesByDate(date);
            
            for (WaitListEntry entry : entries){
                output += entry.getName() + " " + String.valueOf(entry.getDate()) +  " " + String.valueOf(entry.getSeats()) + "\n";
            }
        }
        
        waitListStatusTextArea.setText(output);
    }//GEN-LAST:event_waitListStatusButtonActionPerformed

    private void reserveSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveSubmitButtonActionPerformed
        // TODO add your handling code here:
        Date selectedDate = Date.valueOf(String.valueOf(reserveDateComboBox.getSelectedItem()));
        int selectedSeats = Integer.valueOf(reserveSeatsField.getText().replaceAll("\\s+",""));
        String selectedFaculty = String.valueOf(reserveFacultyComboBox.getSelectedItem());
        
        RoomEntry outRoom = null;
        
        ArrayList<ReservationEntry> reservedOnDate = ReservationQueries.getReservationsByDate(selectedDate);
        ArrayList<RoomEntry> allRoomEntries = RoomQueries.getAllPossibleRooms();
        ArrayList<RoomEntry> reservedRoomEntries = new ArrayList<RoomEntry>();
        
        if (reservedOnDate.size() == 0){
            outRoom = allRoomEntries.get(0);
            
            for(int i = 1; i < allRoomEntries.size(); i++){
                if(allRoomEntries.get(i).getSeats() < outRoom.getSeats()){
                    outRoom = allRoomEntries.get(i);
                }
            }
            
            ReservationEntry entry = new ReservationEntry(selectedFaculty, outRoom.getRoom(), selectedDate, selectedSeats, new Timestamp(Calendar.getInstance().getTime().getTime()));
            ReservationQueries.addReservationEntry(entry);
            
            reserveResultLabel.setText(selectedFaculty + " reserves room " + outRoom.getRoom());
            return;
        }
        
        for (ReservationEntry resEntry : reservedOnDate){
            reservedRoomEntries.add(resEntry.toRoomEntry());
        }
        
        for(RoomEntry room: allRoomEntries){
            boolean notreserved = true;
            for(RoomEntry resRoom: reservedRoomEntries){
                if(room.isEqual(resRoom)){
                    notreserved = false;
                    break;
                }
            }
            if(notreserved && room.getSeats() >= selectedSeats){
                if(outRoom == null){
                    outRoom = room;
                }else if(room.getSeats() < outRoom.getSeats()){
                    outRoom = room;
                }
            }
        }
        
        if(outRoom == null){
            WaitListEntry entry = new WaitListEntry(selectedFaculty, selectedDate, selectedSeats, new Timestamp(Calendar.getInstance().getTime().getTime()));
            WaitListQueries.addWaitListEntry(entry);
            
            reserveResultLabel.setText(selectedFaculty + " gets waitlisted");
        }else{
            ReservationEntry entry = new ReservationEntry(selectedFaculty, outRoom.getRoom(), selectedDate, selectedSeats, new Timestamp(Calendar.getInstance().getTime().getTime()));
            ReservationQueries.addReservationEntry(entry);
            
            reserveResultLabel.setText(selectedFaculty + " reserves room " + outRoom.getRoom());
        }
    }//GEN-LAST:event_reserveSubmitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame dialog = new MainFrame(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
        
        //System.out.println(Dates.getAllDates());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFacultyButton;
    private javax.swing.JTextField addFacultyNameField;
    private javax.swing.JLabel addFacultyNameLabel;
    private javax.swing.JLabel addFacultyResultLabel;
    private javax.swing.JPanel addFacultyTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton resStatusButton;
    private javax.swing.JComboBox<String> resStatusDateComboBox;
    private javax.swing.JTextArea resStatusTextArea;
    private javax.swing.JComboBox<String> reserveDateComboBox;
    private javax.swing.JLabel reserveDateLabel;
    private javax.swing.JComboBox<String> reserveFacultyComboBox;
    private javax.swing.JLabel reserveFacultyLabel;
    private javax.swing.JLabel reserveResultLabel;
    private javax.swing.JTextField reserveSeatsField;
    private javax.swing.JLabel reserveSeatsLabel;
    private javax.swing.JButton reserveSubmitButton;
    private javax.swing.JPanel reserveTab;
    private javax.swing.JTabbedPane tabbedPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton waitListStatusButton;
    private javax.swing.JTextArea waitListStatusTextArea;
    // End of variables declaration//GEN-END:variables
}
